services:
  config:
    container_name: chatappconfig_container
    image: bash
    volumes:
      - ./configdatabase.sh:/app/configdatabase.sh
    entrypoint: ["bash", "-c", "chmod +x ./app/configdatabase.sh && ./app/configdatabase.sh"]
  
  chatappmysqldb:
    container_name: chatappmysqldb_container
    image: mysql
    restart: always
    ports:
      - "${MYSQL_PORT:?error}:3306"
    environment:
    -  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?error}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatapp_mysql_network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    depends_on:
      - config
      
  chatapp:
    container_name: chatapp_container
    image: chatapp
    ports:
        - "${CHAT_APP_PORT:?error}:8080"
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=chatappmysqldb
      - DATABASE_NAME=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      chatappmysqldb:
            condition: service_healthy
    networks:
      - chatapp_mysql_network
    restart: always

networks:
 chatapp_mysql_network:
    driver: bridge
